package com.example.proofloop.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowForward
import androidx.compose.material.icons.filled.CrisisAlert
import androidx.compose.material.icons.filled.Flag
import androidx.compose.material.icons.filled.Psychology
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.proofloop.data.repository.MissionRepository
import com.example.proofloop.theme.AmberGap
import com.example.proofloop.theme.AmberGapGlow
import com.example.proofloop.theme.BgDark
import com.example.proofloop.theme.CyanNeon
import com.example.proofloop.theme.MintProof
import com.example.proofloop.theme.TextMuted
import com.example.proofloop.theme.TextPrimary
import com.example.proofloop.theme.TextSecondary
import com.example.proofloop.ui.components.CompetencyScoreBar
import com.example.proofloop.ui.components.GlassCard
import com.example.proofloop.ui.components.ProofLoopPrimaryButton

@Composable
fun SkillReviewScreen(
    onTryAgainClick: () -> Unit
) {
    val evaluation by MissionRepository.firstEvaluation.collectAsState()
    val scores = evaluation?.scores ?: com.example.proofloop.domain.models.CompetencyScores(
        problemFraming = 88,
        questionQuality = 74,
        rootCauseReasoning = 61,
        communication = 84,
        decisionQuality = 79
    )

    val weakest = scores.getWeakestCompetency()
    val gapName = evaluation?.primaryGap ?: weakest.first
    val feedbackText = evaluation?.feedback ?: "You moved toward a solution before validating multiple possible causes."
    val nextChallengeText = evaluation?.nextChallenge ?: "Before choosing a solution, identify 2 possible causes and explain how you would test each."

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(BgDark)
            .padding(horizontal = 20.dp, vertical = 20.dp)
    ) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Text(
                text = "YOUR SKILL REVIEW",
                color = CyanNeon,
                fontSize = 12.sp,
                fontWeight = FontWeight.ExtraBold,
                letterSpacing = 1.sp
            )

            Box(
                modifier = Modifier
                    .clip(RoundedCornerShape(12.dp))
                    .background(Color(0xFF1E2638))
                    .padding(horizontal = 10.dp, vertical = 4.dp)
            ) {
                Text(
                    text = "ATTEMPT 1",
                    color = TextSecondary,
                    fontSize = 11.sp,
                    fontWeight = FontWeight.Bold
                )
            }
        }

        Spacer(modifier = Modifier.height(14.dp))

        Column(
            modifier = Modifier
                .weight(1f)
                .verticalScroll(rememberScrollState())
        ) {
            Text(
                text = "Competency Breakdown",
                color = TextPrimary,
                fontSize = 24.sp,
                fontWeight = FontWeight.Bold
            )

            Spacer(modifier = Modifier.height(6.dp))

            Text(
                text = "Evaluation generated by analyzing your investigation, interview, defense, and follow-up.",
                color = TextSecondary,
                fontSize = 13.sp,
                lineHeight = 18.sp
            )

            Spacer(modifier = Modifier.height(18.dp))

            // Score Meters
            GlassCard(modifier = Modifier.fillMaxWidth()) {
                Column(modifier = Modifier.fillMaxWidth()) {
                    CompetencyScoreBar(
                        name = "Problem Framing",
                        score = scores.problemFraming
                    )
                    CompetencyScoreBar(
                        name = "Question Quality",
                        score = scores.questionQuality
                    )
                    CompetencyScoreBar(
                        name = "Root-Cause Reasoning",
                        score = scores.rootCauseReasoning,
                        isGap = true,
                        showGapBadge = true
                    )
                    CompetencyScoreBar(
                        name = "Communication",
                        score = scores.communication
                    )
                    CompetencyScoreBar(
                        name = "Decision Quality",
                        score = scores.decisionQuality
                    )
                }
            }

            Spacer(modifier = Modifier.height(20.dp))

            // Highlighted Gap Card
            GlassCard(
                modifier = Modifier.fillMaxWidth(),
                borderColor = AmberGap.copy(alpha = 0.6f),
                backgroundColor = Color(0xFF1A1617)
            ) {
                Column(modifier = Modifier.fillMaxWidth()) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        Icon(
                            imageVector = Icons.Default.CrisisAlert,
                            contentDescription = null,
                            tint = AmberGap,
                            modifier = Modifier.size(18.dp)
                        )
                        Text(
                            text = "YOUR BIGGEST GAP",
                            color = AmberGap,
                            fontSize = 12.sp,
                            fontWeight = FontWeight.Bold,
                            letterSpacing = 0.5.sp
                        )
                    }

                    Spacer(modifier = Modifier.height(10.dp))

                    Text(
                        text = gapName,
                        color = TextPrimary,
                        fontSize = 20.sp,
                        fontWeight = FontWeight.Bold
                    )

                    Spacer(modifier = Modifier.height(6.dp))

                    Text(
                        text = feedbackText,
                        color = Color(0xFFFED7AA),
                        fontSize = 13.sp,
                        lineHeight = 19.sp
                    )
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // Next Challenge Card
            GlassCard(
                modifier = Modifier.fillMaxWidth(),
                borderColor = CyanNeon.copy(alpha = 0.4f),
                backgroundColor = Color(0xFF0E1A29)
            ) {
                Column(modifier = Modifier.fillMaxWidth()) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        Icon(
                            imageVector = Icons.Default.Flag,
                            contentDescription = null,
                            tint = CyanNeon,
                            modifier = Modifier.size(18.dp)
                        )
                        Text(
                            text = "NEXT CHALLENGE",
                            color = CyanNeon,
                            fontSize = 12.sp,
                            fontWeight = FontWeight.Bold,
                            letterSpacing = 0.5.sp
                        )
                    }

                    Spacer(modifier = Modifier.height(8.dp))

                    Text(
                        text = nextChallengeText,
                        color = TextPrimary,
                        fontSize = 14.sp,
                        fontWeight = FontWeight.SemiBold,
                        lineHeight = 20.sp
                    )
                }
            }

            Spacer(modifier = Modifier.height(12.dp))
        }

        ProofLoopPrimaryButton(
            text = "TRY AGAIN",
            icon = Icons.Default.Refresh,
            onClick = onTryAgainClick
        )
    }
}
